Feature/send purchase form
giakhang94/maylanh pull request #12
Opened 2024-07-25 03:21 UTC by giakhang94

https://github.com/giakhang94/maylanh/issues/11
- useForm hook was created in the latest commit: in client/src/service.tsx and client/src/customhook/useForm.ts

2024-07-25 06:02 UTC, trungmt requested changes

2024-07-25 06:02 UTC, trungmt commented on client/src/pages/client/Services.tsx
>    const [showModal, setShowModal] = useState(false);
instead of showModal we could make it like this
```suggestion
  const [selectedService, setSelectedService] = useState(null);
```

When user click on a service to order, call `setSelectedService(service)`
The condition to open modal now change from `showModal && <Modal />` to `!!selectedService && <Modal service ={selectedService}/>`

close modal by setSelectedService(null)

2024-07-25 06:02 UTC, trungmt commented on client/src/pages/client/Services.tsx
>                    handleShowModal();
`setSelectedService(service)`

2024-07-27 03:26 UTC, trungmt requested changes

2024-07-27 06:36 UTC, giakhang94 commented on client/src/components/PurchaseForm.tsx
vất vả vcl, thà là làm gọn ngay từ đầu 
It's hard to re-structure, better if do it at begining

2024-07-27 08:54 UTC, giakhang94 commented on controllers/clientController.js
> +import Client from "../models/clientModel.js";
mai sua cai nay, lấn giờ học av 3 tiếng rồi :))
I'll do this change tomorrow. I had used 3hours of English task for coding today

2024-08-04 15:03 UTC, merged